---
title: "Referencias marco teórico"
author: "JLMR"
date: 2022-01-12T21:13:14-05:00
categories: ["Tesis"]
tags: ["Documentación", "Marco teórico", "Metodología"]
bibliography: citations.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Documentación 

Comentarios generales sobre las perspectiva conceptual de la investigación: 

Se tienen al menos tres vertientes generales: 

+ Desarrollo Comunitario
+ Cambio climático y escenarios de adaptación y mitigación. 
+ Regulación ambiental.


La primera de corte social, la segunda con énfasis en la perspectiva ambiental y la tercera con una combinación por la conceptualización de un marco legal sobre las reservas y areas protegidas.

Comencemos con la perspectiva de corte ambiental: 

Marco teórico metodológico derivado de las recomendaciones del  [IPCC](https://www.ipcc.ch/srccl/chapter/summary-for-policymakers/)

### Degradacción de suelos


Uno de los marcos  conceptuales derivados de los escenarios que planea el **IPCC** es el concepto de **degradación del suelo**  expresado como una 
reducción de largo plazo en la **Productividad Biológica**, **integridad ecológica**. 

En términos metodológicos esta vertiente se asocia a conceptos concretos que requieren de herramientas metodológicas bien definidas que nos permiten mediciones particulares.[@MARTIN2020197]

Definición: **ecological integrity:**   *Ecological integrity is a term often used to describe the state of ecosystems subjected to anthropogenic pressures.*


Cita al margen.  Movimiento  ecologista ya desde la década de los cuarentas del siglo pasado (1949): 

*"A thing is right when it tends to preserve the integrity, stability, and 
beauty of the biotic community.  It is wrong when it tends otherwise” (Leopold, 1949)"*

Para medir indicadores de integridad una metodología común es el contraste de las variables de interés entre dos momentos. ej. *Deviation of an indicator variable from a reference relationship is a measure of integrity.*


## Literatura sobre el Marco teórico. 


### Economía Ecológica.


Un texto sobre la importancia de las variables biofisicas en la concepción teorica de ecological economics[@MELGARMELGAR2020106567].

La relación entre el entono natural y el social bajo la mirada del campo eclogical economics se puede observar en [@SPASH2020106518]. Quines indican enfatizan;   How Nature and society are interrelated raises issues of non-monetary valuation, plural values [@SPASH2020106518].

Este trabajo se cuestiona también el compromiso por el crecimiento que la teoria economica cpnvencional postula. *By the 1980s, amongst economists, Herman Daly was holding the anti-growth fort almost single-handed, until the rise of modern ecological economics* [@SPASH2020106518]. 

# References